apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunalka
  labels:
    app: komunalka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komunalka
  template:
    metadata:
      labels:
        app: komunalka
    spec:
      containers:
      - name: komunalka
        image: ghcr.io/piterpentester/komunalka:sha-3f2f294
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: komunalka-secrets
        volumeMounts:
        - name: db-storage
          mountPath: /app/data
        - name: attachments-storage
          mountPath: /app/attachments
        - name: mapping-config
          mountPath: /app/accounts_to_address_mapping.csv
          subPath: accounts_to_address_mapping.csv
        env:
        - name: DATABASE_URL
          value: "sqlite:////app/data/komunalka.db"
        - name: ACCOUNTS_MAPPING_PATH
          value: "/app/accounts_to_address_mapping.csv"
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: komunalka-db-pvc
      - name: attachments-storage
        persistentVolumeClaim:
          claimName: komunalka-attachments-pvc
      - name: mapping-config
        secret:
          secretName: komunalka-secrets
          items:
          - key: ACCOUNTS_MAPPING_CSV
            path: accounts_to_address_mapping.csv
